import {
  type AgentBrainPort,
  type AgentRepository,
  type AuditLogRepository,
  type ChatMessageRepository,
  type ChatSessionRepository,
  type Clock,
  CreateChatSession,
  CreateTestCase,
  type FeatureRepository,
  GenerateDrafts,
  GetChatEvents,
  type IdGenerator,
  type KnowledgeRetrievalPort,
  type MembershipRepository,
  type ProjectRepository,
  type RunRepository,
  type RunResultRepository,
  type ScenarioRepository,
  SendChatMessage,
  type SliceRepository,
  type SubscriptionRepository,
  type TestCaseRepository,
  type TestKernel,
  ToolBindingRepository,
  TriggerRun,
  type UnitOfWork,
} from '@gilgamesh/application';
import { Module } from '@nestjs/common';
import { TOKENS as T } from '../persistence/tokens';
import { ChatController, ProjectChatController } from './chat.controller';

/**
 * Wires the Agent Chat use cases (slice 8) to the bound ports. The tool whitelist hands
 * SendChatMessage its OWN instances of the EXISTING use cases (TriggerRun / CreateTestCase /
 * GenerateDrafts) so a chat-invoked action follows exactly the standard path — RBAC, quota
 * and audit included.
 */
@Module({
  controllers: [ProjectChatController, ChatController],
  providers: [
    {
      provide: CreateChatSession,
      useFactory: (
        chatSessions: ChatSessionRepository,
        agents: AgentRepository,
        projects: ProjectRepository,
        memberships: MembershipRepository,
        audit: AuditLogRepository,
        ids: IdGenerator,
        clock: Clock,
      ) => new CreateChatSession({ chatSessions, agents, projects, memberships, audit, ids, clock }),
      inject: [T.ChatSessions, T.Agents, T.Projects, T.Memberships, T.Audit, T.Ids, T.Clock],
    },
    {
      provide: SendChatMessage,
      useFactory: (
        chatSessions: ChatSessionRepository,
        chatMessages: ChatMessageRepository,
        projects: ProjectRepository,
        memberships: MembershipRepository,
        agents: AgentRepository,
        toolBindings: ToolBindingRepository,
        features: FeatureRepository,
        brain: AgentBrainPort,
        retrieval: KnowledgeRetrievalPort,
        audit: AuditLogRepository,
        ids: IdGenerator,
        clock: Clock,
        uow: UnitOfWork,
        kernel: TestKernel,
        runs: RunRepository,
        runResults: RunResultRepository,
        scenarios: ScenarioRepository,
        testCases: TestCaseRepository,
        subscriptions: SubscriptionRepository,
        slices: SliceRepository,
      ) =>
        new SendChatMessage({
          chatSessions,
          chatMessages,
          projects,
          memberships,
          agents,
          toolBindings,
          features,
          brain,
          retrieval,
          audit,
          ids,
          clock,
          tools: {
            triggerRun: new TriggerRun({
              uow,
              kernel,
              runs,
              runResults,
              features,
              scenarios,
              testCases,
              subscriptions,
              projects,
              memberships,
              audit,
              ids,
              clock,
            }),
            createTestCase: new CreateTestCase({
              testCases,
              slices,
              agents,
              projects,
              memberships,
              audit,
              ids,
              clock,
            }),
            generateDrafts: new GenerateDrafts({ brain, retrieval, projects, memberships, audit, ids, clock }),
          },
        }),
      inject: [
        T.ChatSessions,
        T.ChatMessages,
        T.Projects,
        T.Memberships,
        T.Agents,
        T.ToolBindings,
        T.Features,
        T.Brain,
        T.KnowledgeRetrieval,
        T.Audit,
        T.Ids,
        T.Clock,
        T.UnitOfWork,
        T.Kernel,
        T.Runs,
        T.RunResults,
        T.Scenarios,
        T.TestCases,
        T.Subscriptions,
        T.Slices,
      ],
    },
    {
      provide: GetChatEvents,
      useFactory: (
        chatSessions: ChatSessionRepository,
        chatMessages: ChatMessageRepository,
        projects: ProjectRepository,
        memberships: MembershipRepository,
      ) => new GetChatEvents({ chatSessions, chatMessages, projects, memberships }),
      inject: [T.ChatSessions, T.ChatMessages, T.Projects, T.Memberships],
    },
  ],
})
export class ChatModule {}
