import {
  type AgentRepository,
  type AuditLogRepository,
  type AgentBrainPort,
  ApplyPaymentEvent,
  BrainBilling,
  type BrainTokenMeter,
  type BrainUsageRepository,
  type Clock,
  DeterministicKernel,
  type IdGenerator,
  type InvoiceRepository,
  type KnowledgeChunkRepository,
  type KnowledgeDocumentRepository,
  KnowledgeRetriever,
  MockRepoProvider,
  InMemoryAgentRepository,
  InMemoryAuditLogRepository,
  InMemoryBrainUsageRepository,
  InMemoryChatMessageRepository,
  InMemoryChatSessionRepository,
  InMemoryEventBus,
  InMemoryFeatureRepository,
  InMemoryIntegrationRepository,
  InMemoryInvoiceRepository,
  InMemoryKnowledgeChunkRepository,
  InMemoryKnowledgeDocumentRepository,
  InMemoryMembershipRepository,
  InMemoryOrgRepository,
  InMemoryPasswordResetRepository,
  InMemoryProjectRepository,
  InMemoryRunRepository,
  InMemoryRunResultRepository,
  InMemoryScenarioRepository,
  InMemorySessionRepository,
  InMemorySliceRepository,
  InMemorySubscriptionRepository,
  InMemoryTestCaseRepository,
  InMemoryToolBindingRepository,
  InMemoryUnitOfWork,
  InMemoryUserRepository,
  type FeatureRepository,
  type IntegrationRepository,
  type MembershipRepository,
  type OrgRepository,
  type PasswordResetRepository,
  type ProjectRepository,
  type RunRepository,
  type RunResultRepository,
  type ScenarioRepository,
  type SecretVault,
  type SessionRepository,
  type SliceRepository,
  type SubscriptionRepository,
  type TestCaseRepository,
  type ToolBindingRepository,
  type UnitOfWork,
  type UserRepository,
} from '@gilgamesh/application';
import { Global, Module } from '@nestjs/common';
import {
  Argon2PasswordHasher,
  brainFromEnv,
  brainKeyVerifierFromEnv,
  CryptoSessionTokenGenerator,
  emailFromEnv,
  paymentsFromEnv,
  SystemClock,
  Uuid7IdGenerator,
  vaultFromEnv,
} from '../infra';
import { AlwaysReadyProbe } from '../health/always-ready.probe';
import { TOKENS } from './tokens';

/**
 * Wires the application ports to concrete adapters. Repositories are the in-memory
 * adapters for now (swapped for Prisma once the DB is available); the security infra
 * (Argon2id, UUID v7, crypto session tokens, system clock) is production-grade already.
 */
@Global()
@Module({
  providers: [
    { provide: TOKENS.Users, useValue: new InMemoryUserRepository() },
    { provide: TOKENS.Orgs, useValue: new InMemoryOrgRepository() },
    { provide: TOKENS.Memberships, useValue: new InMemoryMembershipRepository() },
    { provide: TOKENS.Sessions, useValue: new InMemorySessionRepository() },
    { provide: TOKENS.PasswordResets, useValue: new InMemoryPasswordResetRepository() },
    // Provider selection (S17, the S9-1 pattern): the S12 recording stub unless EMAIL_MODE/
    // SMTP_URL select the real nodemailer SMTP adapter. Every harness pins EMAIL_MODE=offline,
    // so BDD/e2e keep reading recorded mail via this token.
    { provide: TOKENS.Email, useFactory: () => emailFromEnv() },
    { provide: TOKENS.Projects, useValue: new InMemoryProjectRepository() },
    { provide: TOKENS.Slices, useValue: new InMemorySliceRepository() },
    { provide: TOKENS.Features, useValue: new InMemoryFeatureRepository() },
    { provide: TOKENS.Scenarios, useValue: new InMemoryScenarioRepository() },
    { provide: TOKENS.TestCases, useValue: new InMemoryTestCaseRepository() },
    { provide: TOKENS.Runs, useValue: new InMemoryRunRepository() },
    { provide: TOKENS.RunResults, useValue: new InMemoryRunResultRepository() },
    { provide: TOKENS.Agents, useValue: new InMemoryAgentRepository() },
    { provide: TOKENS.ToolBindings, useValue: new InMemoryToolBindingRepository() },
    { provide: TOKENS.Subscriptions, useValue: new InMemorySubscriptionRepository() },
    { provide: TOKENS.Invoices, useValue: new InMemoryInvoiceRepository() },
    { provide: TOKENS.Audit, useValue: new InMemoryAuditLogRepository() },
    {
      // Wraps the SAME repo instances bound to the tokens above, so transactional writes
      // and direct reads share one store (the in-memory UoW has no real rollback).
      provide: TOKENS.UnitOfWork,
      useFactory: (
        users: UserRepository,
        orgs: OrgRepository,
        memberships: MembershipRepository,
        sessions: SessionRepository,
        passwordResets: PasswordResetRepository,
        projects: ProjectRepository,
        slices: SliceRepository,
        features: FeatureRepository,
        scenarios: ScenarioRepository,
        testCases: TestCaseRepository,
        runs: RunRepository,
        runResults: RunResultRepository,
        agents: AgentRepository,
        toolBindings: ToolBindingRepository,
        subscriptions: SubscriptionRepository,
        invoices: InvoiceRepository,
        audit: AuditLogRepository,
        knowledge: KnowledgeChunkRepository,
        knowledgeDocuments: KnowledgeDocumentRepository,
        brainUsage: BrainUsageRepository,
      ) =>
        new InMemoryUnitOfWork({
          users,
          orgs,
          memberships,
          sessions,
          passwordResets,
          projects,
          slices,
          features,
          scenarios,
          testCases,
          runs,
          runResults,
          agents,
          toolBindings,
          subscriptions,
          invoices,
          audit,
          knowledge,
          knowledgeDocuments,
          brainUsage,
        }),
      inject: [
        TOKENS.Users,
        TOKENS.Orgs,
        TOKENS.Memberships,
        TOKENS.Sessions,
        TOKENS.PasswordResets,
        TOKENS.Projects,
        TOKENS.Slices,
        TOKENS.Features,
        TOKENS.Scenarios,
        TOKENS.TestCases,
        TOKENS.Runs,
        TOKENS.RunResults,
        TOKENS.Agents,
        TOKENS.ToolBindings,
        TOKENS.Subscriptions,
        TOKENS.Invoices,
        TOKENS.Audit,
        TOKENS.Knowledge,
        TOKENS.KnowledgeDocuments,
        TOKENS.BrainUsage,
      ],
    },
    {
      // Slice 14: the shared token check/charge seam — the BrainUsage row and the
      // Subscription.brainTokensUsed increment commit in one UoW transaction.
      provide: TOKENS.BrainBilling,
      useFactory: (uow: UnitOfWork, subscriptions: SubscriptionRepository, ids: IdGenerator, clock: Clock) =>
        new BrainBilling({ uow, subscriptions, ids, clock }),
      inject: [TOKENS.UnitOfWork, TOKENS.Subscriptions, TOKENS.Ids, TOKENS.Clock],
    },
    { provide: TOKENS.Hasher, useValue: new Argon2PasswordHasher() },
    { provide: TOKENS.Ids, useValue: new Uuid7IdGenerator() },
    { provide: TOKENS.Tokens, useValue: new CryptoSessionTokenGenerator() },
    { provide: TOKENS.Clock, useValue: new SystemClock() },
    // Provider selection (S9-1): the stub unless BRAIN_MODE/ANTHROPIC_API_KEY select the real
    // Claude adapter; the key verifier follows the same mode (real 1-token ping only in auto).
    // In auto, `forOrg` resolves a connected org BYOK key per call (integrations row + vault).
    {
      provide: TOKENS.Brain,
      useFactory: (integrations: IntegrationRepository, vault: SecretVault) =>
        brainFromEnv(process.env, { integrations, vault }),
      inject: [TOKENS.Integrations, TOKENS.SecretVault],
    },
    { provide: TOKENS.BrainKeys, useFactory: () => brainKeyVerifierFromEnv() },
    { provide: TOKENS.BrainUsage, useValue: new InMemoryBrainUsageRepository() },
    { provide: TOKENS.Events, useValue: new InMemoryEventBus() },
    { provide: TOKENS.Kernel, useValue: new DeterministicKernel() },
    // Provider selection (S13-B, the brain pattern): the deterministic mock unless PAYMENTS_MODE/
    // STRIPE_SECRET_KEY select the real Stripe adapter. Both share the ApplyPaymentEvent seam and
    // the local Invoice store, so webhooks and the confirm flow persist identically.
    {
      provide: TOKENS.Payment,
      useFactory: (
        uow: UnitOfWork,
        ids: IdGenerator,
        clock: Clock,
        invoices: InvoiceRepository,
        subscriptions: SubscriptionRepository,
      ) =>
        paymentsFromEnv(process.env, {
          events: new ApplyPaymentEvent({ uow, ids, clock }),
          invoices,
          subscriptions,
          // S40: the clock drives the deterministic prorated-refund amount.
          clock,
        }),
      inject: [TOKENS.UnitOfWork, TOKENS.Ids, TOKENS.Clock, TOKENS.Invoices, TOKENS.Subscriptions],
    },
    { provide: TOKENS.Knowledge, useValue: new InMemoryKnowledgeChunkRepository() },
    { provide: TOKENS.KnowledgeDocuments, useValue: new InMemoryKnowledgeDocumentRepository() },
    {
      provide: TOKENS.KnowledgeRetrieval,
      // S16 metering + S14 charging: scoped grounding writes EMBED rows AND charges the filter org.
      useFactory: (brain: AgentBrainPort, knowledge: KnowledgeChunkRepository, meter: BrainTokenMeter) =>
        new KnowledgeRetriever({ brain, knowledge, meter }),
      inject: [TOKENS.Brain, TOKENS.Knowledge, TOKENS.BrainBilling],
    },
    { provide: TOKENS.ChatSessions, useValue: new InMemoryChatSessionRepository() },
    { provide: TOKENS.ChatMessages, useValue: new InMemoryChatMessageRepository() },
    { provide: TOKENS.Integrations, useValue: new InMemoryIntegrationRepository() },
    { provide: TOKENS.RepoProvider, useValue: new MockRepoProvider() },
    // Provider selection (S20, the S15 security INVERSION): explicit VAULT_MODE=offline → the
    // in-memory stub (refused under NODE_ENV=production); AZURE_KEY_VAULT_URL → Azure Key Vault;
    // anything else REFUSES TO BOOT — a silently selected vault stub would hold live BYOK keys
    // in process memory. Every harness pins VAULT_MODE=offline.
    { provide: TOKENS.SecretVault, useFactory: () => vaultFromEnv() },
    // Slice 27: readiness — the in-memory store is in-process, so always ready. The HealthController
    // (declared in the app module that imports this @Global module) injects this token.
    { provide: TOKENS.Readiness, useValue: new AlwaysReadyProbe() },
  ],
  exports: [
    TOKENS.Users,
    TOKENS.Orgs,
    TOKENS.Memberships,
    TOKENS.Sessions,
    TOKENS.PasswordResets,
    TOKENS.Email,
    TOKENS.Projects,
    TOKENS.Slices,
    TOKENS.Features,
    TOKENS.Scenarios,
    TOKENS.TestCases,
    TOKENS.Runs,
    TOKENS.RunResults,
    TOKENS.Agents,
    TOKENS.ToolBindings,
    TOKENS.Subscriptions,
    TOKENS.Invoices,
    TOKENS.Audit,
    TOKENS.UnitOfWork,
    TOKENS.Hasher,
    TOKENS.Ids,
    TOKENS.Tokens,
    TOKENS.Clock,
    TOKENS.Brain,
    TOKENS.BrainKeys,
    TOKENS.BrainUsage,
    TOKENS.BrainBilling,
    TOKENS.Events,
    TOKENS.Kernel,
    TOKENS.Payment,
    TOKENS.Knowledge,
    TOKENS.KnowledgeDocuments,
    TOKENS.KnowledgeRetrieval,
    TOKENS.ChatSessions,
    TOKENS.ChatMessages,
    TOKENS.Integrations,
    TOKENS.RepoProvider,
    TOKENS.SecretVault,
    TOKENS.Readiness,
  ],
})
export class PersistenceModule {}
