import {
  type AgentRepository,
  type AuditLogRepository,
  type AgentBrainPort,
  DeterministicKernel,
  type KnowledgeChunkRepository,
  type KnowledgeDocumentRepository,
  KnowledgeRetriever,
  MockPaymentProvider,
  MockRepoProvider,
  StubSecretVault,
  InMemoryAgentRepository,
  InMemoryAuditLogRepository,
  InMemoryBrainUsageRepository,
  InMemoryChatMessageRepository,
  InMemoryChatSessionRepository,
  InMemoryEventBus,
  InMemoryFeatureRepository,
  InMemoryIntegrationRepository,
  InMemoryKnowledgeChunkRepository,
  InMemoryKnowledgeDocumentRepository,
  InMemoryMembershipRepository,
  InMemoryOrgRepository,
  InMemoryPasswordResetRepository,
  InMemoryProjectRepository,
  InMemoryRunRepository,
  InMemoryRunResultRepository,
  InMemoryScenarioRepository,
  InMemorySessionRepository,
  InMemorySliceRepository,
  InMemorySubscriptionRepository,
  InMemoryTestCaseRepository,
  InMemoryToolBindingRepository,
  InMemoryUnitOfWork,
  InMemoryUserRepository,
  type FeatureRepository,
  type IntegrationRepository,
  type MembershipRepository,
  type OrgRepository,
  type ProjectRepository,
  type RunRepository,
  type RunResultRepository,
  type ScenarioRepository,
  type SecretVault,
  type SessionRepository,
  type SliceRepository,
  type SubscriptionRepository,
  type TestCaseRepository,
  type ToolBindingRepository,
  type UserRepository,
} from '@gilgamesh/application';
import { Global, Module } from '@nestjs/common';
import {
  Argon2PasswordHasher,
  brainFromEnv,
  brainKeyVerifierFromEnv,
  CryptoSessionTokenGenerator,
  emailFromEnv,
  SystemClock,
  Uuid7IdGenerator,
} from '../infra';
import { TOKENS } from './tokens';

/**
 * Wires the application ports to concrete adapters. Repositories are the in-memory
 * adapters for now (swapped for Prisma once the DB is available); the security infra
 * (Argon2id, UUID v7, crypto session tokens, system clock) is production-grade already.
 */
@Global()
@Module({
  providers: [
    { provide: TOKENS.Users, useValue: new InMemoryUserRepository() },
    { provide: TOKENS.Orgs, useValue: new InMemoryOrgRepository() },
    { provide: TOKENS.Memberships, useValue: new InMemoryMembershipRepository() },
    { provide: TOKENS.Sessions, useValue: new InMemorySessionRepository() },
    { provide: TOKENS.PasswordResets, useValue: new InMemoryPasswordResetRepository() },
    // Provider selection (S17, the S9-1 pattern): the S12 recording stub unless EMAIL_MODE/
    // SMTP_URL select the real nodemailer SMTP adapter. Every harness pins EMAIL_MODE=offline,
    // so BDD/e2e keep reading recorded mail via this token.
    { provide: TOKENS.Email, useFactory: () => emailFromEnv() },
    { provide: TOKENS.Projects, useValue: new InMemoryProjectRepository() },
    { provide: TOKENS.Slices, useValue: new InMemorySliceRepository() },
    { provide: TOKENS.Features, useValue: new InMemoryFeatureRepository() },
    { provide: TOKENS.Scenarios, useValue: new InMemoryScenarioRepository() },
    { provide: TOKENS.TestCases, useValue: new InMemoryTestCaseRepository() },
    { provide: TOKENS.Runs, useValue: new InMemoryRunRepository() },
    { provide: TOKENS.RunResults, useValue: new InMemoryRunResultRepository() },
    { provide: TOKENS.Agents, useValue: new InMemoryAgentRepository() },
    { provide: TOKENS.ToolBindings, useValue: new InMemoryToolBindingRepository() },
    { provide: TOKENS.Subscriptions, useValue: new InMemorySubscriptionRepository() },
    { provide: TOKENS.Audit, useValue: new InMemoryAuditLogRepository() },
    {
      // Wraps the SAME repo instances bound to the tokens above, so transactional writes
      // and direct reads share one store (the in-memory UoW has no real rollback).
      provide: TOKENS.UnitOfWork,
      useFactory: (
        users: UserRepository,
        orgs: OrgRepository,
        memberships: MembershipRepository,
        sessions: SessionRepository,
        projects: ProjectRepository,
        slices: SliceRepository,
        features: FeatureRepository,
        scenarios: ScenarioRepository,
        testCases: TestCaseRepository,
        runs: RunRepository,
        runResults: RunResultRepository,
        agents: AgentRepository,
        toolBindings: ToolBindingRepository,
        subscriptions: SubscriptionRepository,
        audit: AuditLogRepository,
        knowledge: KnowledgeChunkRepository,
        knowledgeDocuments: KnowledgeDocumentRepository,
      ) =>
        new InMemoryUnitOfWork({
          users,
          orgs,
          memberships,
          sessions,
          projects,
          slices,
          features,
          scenarios,
          testCases,
          runs,
          runResults,
          agents,
          toolBindings,
          subscriptions,
          audit,
          knowledge,
          knowledgeDocuments,
        }),
      inject: [
        TOKENS.Users,
        TOKENS.Orgs,
        TOKENS.Memberships,
        TOKENS.Sessions,
        TOKENS.Projects,
        TOKENS.Slices,
        TOKENS.Features,
        TOKENS.Scenarios,
        TOKENS.TestCases,
        TOKENS.Runs,
        TOKENS.RunResults,
        TOKENS.Agents,
        TOKENS.ToolBindings,
        TOKENS.Subscriptions,
        TOKENS.Audit,
        TOKENS.Knowledge,
        TOKENS.KnowledgeDocuments,
      ],
    },
    { provide: TOKENS.Hasher, useValue: new Argon2PasswordHasher() },
    { provide: TOKENS.Ids, useValue: new Uuid7IdGenerator() },
    { provide: TOKENS.Tokens, useValue: new CryptoSessionTokenGenerator() },
    { provide: TOKENS.Clock, useValue: new SystemClock() },
    // Provider selection (S9-1): the stub unless BRAIN_MODE/ANTHROPIC_API_KEY select the real
    // Claude adapter; the key verifier follows the same mode (real 1-token ping only in auto).
    // In auto, `forOrg` resolves a connected org BYOK key per call (integrations row + vault).
    {
      provide: TOKENS.Brain,
      useFactory: (integrations: IntegrationRepository, vault: SecretVault) =>
        brainFromEnv(process.env, { integrations, vault }),
      inject: [TOKENS.Integrations, TOKENS.SecretVault],
    },
    { provide: TOKENS.BrainKeys, useFactory: () => brainKeyVerifierFromEnv() },
    { provide: TOKENS.BrainUsage, useValue: new InMemoryBrainUsageRepository() },
    { provide: TOKENS.Events, useValue: new InMemoryEventBus() },
    { provide: TOKENS.Kernel, useValue: new DeterministicKernel() },
    { provide: TOKENS.Payment, useValue: new MockPaymentProvider() },
    { provide: TOKENS.Knowledge, useValue: new InMemoryKnowledgeChunkRepository() },
    { provide: TOKENS.KnowledgeDocuments, useValue: new InMemoryKnowledgeDocumentRepository() },
    {
      provide: TOKENS.KnowledgeRetrieval,
      useFactory: (brain: AgentBrainPort, knowledge: KnowledgeChunkRepository) =>
        new KnowledgeRetriever({ brain, knowledge }),
      inject: [TOKENS.Brain, TOKENS.Knowledge],
    },
    { provide: TOKENS.ChatSessions, useValue: new InMemoryChatSessionRepository() },
    { provide: TOKENS.ChatMessages, useValue: new InMemoryChatMessageRepository() },
    { provide: TOKENS.Integrations, useValue: new InMemoryIntegrationRepository() },
    { provide: TOKENS.RepoProvider, useValue: new MockRepoProvider() },
    { provide: TOKENS.SecretVault, useValue: new StubSecretVault() },
  ],
  exports: [
    TOKENS.Users,
    TOKENS.Orgs,
    TOKENS.Memberships,
    TOKENS.Sessions,
    TOKENS.PasswordResets,
    TOKENS.Email,
    TOKENS.Projects,
    TOKENS.Slices,
    TOKENS.Features,
    TOKENS.Scenarios,
    TOKENS.TestCases,
    TOKENS.Runs,
    TOKENS.RunResults,
    TOKENS.Agents,
    TOKENS.ToolBindings,
    TOKENS.Subscriptions,
    TOKENS.Audit,
    TOKENS.UnitOfWork,
    TOKENS.Hasher,
    TOKENS.Ids,
    TOKENS.Tokens,
    TOKENS.Clock,
    TOKENS.Brain,
    TOKENS.BrainKeys,
    TOKENS.BrainUsage,
    TOKENS.Events,
    TOKENS.Kernel,
    TOKENS.Payment,
    TOKENS.Knowledge,
    TOKENS.KnowledgeDocuments,
    TOKENS.KnowledgeRetrieval,
    TOKENS.ChatSessions,
    TOKENS.ChatMessages,
    TOKENS.Integrations,
    TOKENS.RepoProvider,
    TOKENS.SecretVault,
  ],
})
export class PersistenceModule {}
