import {
  type AgentRepository,
  type AuditLogRepository,
  type AgentBrainPort,
  DeterministicBrain,
  DeterministicKernel,
  type KnowledgeChunkRepository,
  type KnowledgeDocumentRepository,
  KnowledgeRetriever,
  MockPaymentProvider,
  MockRepoProvider,
  StubSecretVault,
  InMemoryAgentRepository,
  InMemoryAuditLogRepository,
  InMemoryChatMessageRepository,
  InMemoryChatSessionRepository,
  InMemoryFeatureRepository,
  InMemoryIntegrationRepository,
  InMemoryKnowledgeChunkRepository,
  InMemoryKnowledgeDocumentRepository,
  InMemoryMembershipRepository,
  InMemoryOrgRepository,
  InMemoryProjectRepository,
  InMemoryRunRepository,
  InMemoryRunResultRepository,
  InMemoryScenarioRepository,
  InMemorySessionRepository,
  InMemorySliceRepository,
  InMemorySubscriptionRepository,
  InMemoryTestCaseRepository,
  InMemoryToolBindingRepository,
  InMemoryUnitOfWork,
  InMemoryUserRepository,
  type FeatureRepository,
  type MembershipRepository,
  type OrgRepository,
  type ProjectRepository,
  type RunRepository,
  type RunResultRepository,
  type ScenarioRepository,
  type SessionRepository,
  type SliceRepository,
  type SubscriptionRepository,
  type TestCaseRepository,
  type ToolBindingRepository,
  type UserRepository,
} from '@gilgamesh/application';
import { Global, Module } from '@nestjs/common';
import {
  Argon2PasswordHasher,
  CryptoSessionTokenGenerator,
  SystemClock,
  Uuid7IdGenerator,
} from '../infra';
import { TOKENS } from './tokens';

/**
 * Wires the application ports to concrete adapters. Repositories are the in-memory
 * adapters for now (swapped for Prisma once the DB is available); the security infra
 * (Argon2id, UUID v7, crypto session tokens, system clock) is production-grade already.
 */
@Global()
@Module({
  providers: [
    { provide: TOKENS.Users, useValue: new InMemoryUserRepository() },
    { provide: TOKENS.Orgs, useValue: new InMemoryOrgRepository() },
    { provide: TOKENS.Memberships, useValue: new InMemoryMembershipRepository() },
    { provide: TOKENS.Sessions, useValue: new InMemorySessionRepository() },
    { provide: TOKENS.Projects, useValue: new InMemoryProjectRepository() },
    { provide: TOKENS.Slices, useValue: new InMemorySliceRepository() },
    { provide: TOKENS.Features, useValue: new InMemoryFeatureRepository() },
    { provide: TOKENS.Scenarios, useValue: new InMemoryScenarioRepository() },
    { provide: TOKENS.TestCases, useValue: new InMemoryTestCaseRepository() },
    { provide: TOKENS.Runs, useValue: new InMemoryRunRepository() },
    { provide: TOKENS.RunResults, useValue: new InMemoryRunResultRepository() },
    { provide: TOKENS.Agents, useValue: new InMemoryAgentRepository() },
    { provide: TOKENS.ToolBindings, useValue: new InMemoryToolBindingRepository() },
    { provide: TOKENS.Subscriptions, useValue: new InMemorySubscriptionRepository() },
    { provide: TOKENS.Audit, useValue: new InMemoryAuditLogRepository() },
    {
      // Wraps the SAME repo instances bound to the tokens above, so transactional writes
      // and direct reads share one store (the in-memory UoW has no real rollback).
      provide: TOKENS.UnitOfWork,
      useFactory: (
        users: UserRepository,
        orgs: OrgRepository,
        memberships: MembershipRepository,
        sessions: SessionRepository,
        projects: ProjectRepository,
        slices: SliceRepository,
        features: FeatureRepository,
        scenarios: ScenarioRepository,
        testCases: TestCaseRepository,
        runs: RunRepository,
        runResults: RunResultRepository,
        agents: AgentRepository,
        toolBindings: ToolBindingRepository,
        subscriptions: SubscriptionRepository,
        audit: AuditLogRepository,
        knowledge: KnowledgeChunkRepository,
        knowledgeDocuments: KnowledgeDocumentRepository,
      ) =>
        new InMemoryUnitOfWork({
          users,
          orgs,
          memberships,
          sessions,
          projects,
          slices,
          features,
          scenarios,
          testCases,
          runs,
          runResults,
          agents,
          toolBindings,
          subscriptions,
          audit,
          knowledge,
          knowledgeDocuments,
        }),
      inject: [
        TOKENS.Users,
        TOKENS.Orgs,
        TOKENS.Memberships,
        TOKENS.Sessions,
        TOKENS.Projects,
        TOKENS.Slices,
        TOKENS.Features,
        TOKENS.Scenarios,
        TOKENS.TestCases,
        TOKENS.Runs,
        TOKENS.RunResults,
        TOKENS.Agents,
        TOKENS.ToolBindings,
        TOKENS.Subscriptions,
        TOKENS.Audit,
        TOKENS.Knowledge,
        TOKENS.KnowledgeDocuments,
      ],
    },
    { provide: TOKENS.Hasher, useValue: new Argon2PasswordHasher() },
    { provide: TOKENS.Ids, useValue: new Uuid7IdGenerator() },
    { provide: TOKENS.Tokens, useValue: new CryptoSessionTokenGenerator() },
    { provide: TOKENS.Clock, useValue: new SystemClock() },
    { provide: TOKENS.Brain, useValue: new DeterministicBrain() },
    { provide: TOKENS.Kernel, useValue: new DeterministicKernel() },
    { provide: TOKENS.Payment, useValue: new MockPaymentProvider() },
    { provide: TOKENS.Knowledge, useValue: new InMemoryKnowledgeChunkRepository() },
    { provide: TOKENS.KnowledgeDocuments, useValue: new InMemoryKnowledgeDocumentRepository() },
    {
      provide: TOKENS.KnowledgeRetrieval,
      useFactory: (brain: AgentBrainPort, knowledge: KnowledgeChunkRepository) =>
        new KnowledgeRetriever({ brain, knowledge }),
      inject: [TOKENS.Brain, TOKENS.Knowledge],
    },
    { provide: TOKENS.ChatSessions, useValue: new InMemoryChatSessionRepository() },
    { provide: TOKENS.ChatMessages, useValue: new InMemoryChatMessageRepository() },
    { provide: TOKENS.Integrations, useValue: new InMemoryIntegrationRepository() },
    { provide: TOKENS.RepoProvider, useValue: new MockRepoProvider() },
    { provide: TOKENS.SecretVault, useValue: new StubSecretVault() },
  ],
  exports: [
    TOKENS.Users,
    TOKENS.Orgs,
    TOKENS.Memberships,
    TOKENS.Sessions,
    TOKENS.Projects,
    TOKENS.Slices,
    TOKENS.Features,
    TOKENS.Scenarios,
    TOKENS.TestCases,
    TOKENS.Runs,
    TOKENS.RunResults,
    TOKENS.Agents,
    TOKENS.ToolBindings,
    TOKENS.Subscriptions,
    TOKENS.Audit,
    TOKENS.UnitOfWork,
    TOKENS.Hasher,
    TOKENS.Ids,
    TOKENS.Tokens,
    TOKENS.Clock,
    TOKENS.Brain,
    TOKENS.Kernel,
    TOKENS.Payment,
    TOKENS.Knowledge,
    TOKENS.KnowledgeDocuments,
    TOKENS.KnowledgeRetrieval,
    TOKENS.ChatSessions,
    TOKENS.ChatMessages,
    TOKENS.Integrations,
    TOKENS.RepoProvider,
    TOKENS.SecretVault,
  ],
})
export class PersistenceModule {}
