/** DI tokens for the application ports (repositories + infra adapters). */
export const TOKENS = {
  Users: 'UserRepository',
  Orgs: 'OrgRepository',
  Memberships: 'MembershipRepository',
  Sessions: 'SessionRepository',
  PasswordResets: 'PasswordResetRepository',
  Email: 'EmailPort',
  Projects: 'ProjectRepository',
  Slices: 'SliceRepository',
  Features: 'FeatureRepository',
  Scenarios: 'ScenarioRepository',
  TestCases: 'TestCaseRepository',
  Runs: 'RunRepository',
  RunResults: 'RunResultRepository',
  Agents: 'AgentRepository',
  ToolBindings: 'ToolBindingRepository',
  Subscriptions: 'SubscriptionRepository',
  Invoices: 'InvoiceRepository',
  Audit: 'AuditLogRepository',
  UnitOfWork: 'UnitOfWork',
  Hasher: 'PasswordHasher',
  Ids: 'IdGenerator',
  Tokens: 'TokenGenerator',
  Clock: 'Clock',
  Brain: 'AgentBrainPort',
  // Slice 42: STT/TTS behind the VoicePort — DeterministicVoice offline, Azure Speech when configured.
  Voice: 'VOICE',
  Kernel: 'TestKernel',
  Payment: 'PaymentProvider',
  Knowledge: 'KnowledgeChunkRepository',
  KnowledgeDocuments: 'KnowledgeDocumentRepository',
  KnowledgeRetrieval: 'KnowledgeRetrievalPort',
  ChatSessions: 'ChatSessionRepository',
  ChatMessages: 'ChatMessageRepository',
  BrainUsage: 'BrainUsageRepository',
  // Slice 14: the shared token check/charge seam (BrainUsage row + brainTokensUsed, atomically).
  BrainBilling: 'BrainBilling',
  Events: 'EventBus',
  BrainKeys: 'BrainKeyVerifier',
  Integrations: 'IntegrationRepository',
  RepoProvider: 'RepoProvider',
  SecretVault: 'SecretVault',
  // Slice 15 (SSO): bound in the AuthModule, not the persistence wirings — transport-security
  // plumbing (the RateLimitStore precedent). The Redis SsoStateStore swap happens there later.
  Identity: 'IdentityProvider',
  SsoStates: 'SsoStateStore',
  // Slice 27: readiness DB probe (SELECT 1). Bound per persistence wiring — AlwaysReadyProbe
  // (in-memory) / PrismaReadinessProbe (Postgres) — and injected into the HealthController.
  Readiness: 'ReadinessProbe',
} as const;
