import {
  type AgentBrainPort,
  DeterministicKernel,
  InMemoryEventBus,
  type KnowledgeChunkRepository,
  KnowledgeRetriever,
  MockPaymentProvider,
  MockRepoProvider,
  StubSecretVault,
} from '@gilgamesh/application';
import { Global, Module } from '@nestjs/common';
import {
  Argon2PasswordHasher,
  brainFromEnv,
  brainKeyVerifierFromEnv,
  CryptoSessionTokenGenerator,
  SystemClock,
  Uuid7IdGenerator,
} from '../../infra';
import { TOKENS } from '../tokens';
import { PrismaService } from './prisma.service';
import {
  PrismaAgentRepository,
  PrismaAuditLogRepository,
  PrismaBrainUsageRepository,
  PrismaChatMessageRepository,
  PrismaChatSessionRepository,
  PrismaFeatureRepository,
  PrismaIntegrationRepository,
  PrismaKnowledgeChunkRepository,
  PrismaKnowledgeDocumentRepository,
  PrismaMembershipRepository,
  PrismaOrgRepository,
  PrismaProjectRepository,
  PrismaRunRepository,
  PrismaRunResultRepository,
  PrismaScenarioRepository,
  PrismaSessionRepository,
  PrismaSliceRepository,
  PrismaSubscriptionRepository,
  PrismaTestCaseRepository,
  PrismaToolBindingRepository,
  PrismaUserRepository,
} from './prisma-repositories';
import { PrismaUnitOfWork } from './prisma-unit-of-work';

/** Production persistence: Prisma-backed repositories (real Postgres) + security infra. */
@Global()
@Module({
  providers: [
    PrismaService,
    { provide: TOKENS.Users, useFactory: (db: PrismaService) => new PrismaUserRepository(db), inject: [PrismaService] },
    { provide: TOKENS.Orgs, useFactory: (db: PrismaService) => new PrismaOrgRepository(db), inject: [PrismaService] },
    { provide: TOKENS.Memberships, useFactory: (db: PrismaService) => new PrismaMembershipRepository(db), inject: [PrismaService] },
    { provide: TOKENS.Sessions, useFactory: (db: PrismaService) => new PrismaSessionRepository(db), inject: [PrismaService] },
    { provide: TOKENS.Projects, useFactory: (db: PrismaService) => new PrismaProjectRepository(db), inject: [PrismaService] },
    { provide: TOKENS.Slices, useFactory: (db: PrismaService) => new PrismaSliceRepository(db), inject: [PrismaService] },
    { provide: TOKENS.Features, useFactory: (db: PrismaService) => new PrismaFeatureRepository(db), inject: [PrismaService] },
    { provide: TOKENS.Scenarios, useFactory: (db: PrismaService) => new PrismaScenarioRepository(db), inject: [PrismaService] },
    { provide: TOKENS.TestCases, useFactory: (db: PrismaService) => new PrismaTestCaseRepository(db), inject: [PrismaService] },
    { provide: TOKENS.Runs, useFactory: (db: PrismaService) => new PrismaRunRepository(db), inject: [PrismaService] },
    { provide: TOKENS.RunResults, useFactory: (db: PrismaService) => new PrismaRunResultRepository(db), inject: [PrismaService] },
    { provide: TOKENS.Agents, useFactory: (db: PrismaService) => new PrismaAgentRepository(db), inject: [PrismaService] },
    { provide: TOKENS.ToolBindings, useFactory: (db: PrismaService) => new PrismaToolBindingRepository(db), inject: [PrismaService] },
    { provide: TOKENS.Subscriptions, useFactory: (db: PrismaService) => new PrismaSubscriptionRepository(db), inject: [PrismaService] },
    { provide: TOKENS.Audit, useFactory: (db: PrismaService) => new PrismaAuditLogRepository(db), inject: [PrismaService] },
    { provide: TOKENS.UnitOfWork, useFactory: (db: PrismaService) => new PrismaUnitOfWork(db), inject: [PrismaService] },
    { provide: TOKENS.Hasher, useValue: new Argon2PasswordHasher() },
    { provide: TOKENS.Ids, useValue: new Uuid7IdGenerator() },
    { provide: TOKENS.Tokens, useValue: new CryptoSessionTokenGenerator() },
    { provide: TOKENS.Clock, useValue: new SystemClock() },
    // Provider selection (S9-1): the stub unless BRAIN_MODE/ANTHROPIC_API_KEY select the real
    // Claude adapter; the key verifier follows the same mode. The EventBus stays in-process
    // in-memory (one API replica) — a Redis pub/sub swap is wiring-only later.
    { provide: TOKENS.Brain, useFactory: () => brainFromEnv() },
    { provide: TOKENS.BrainKeys, useFactory: () => brainKeyVerifierFromEnv() },
    { provide: TOKENS.Events, useValue: new InMemoryEventBus() },
    {
      provide: TOKENS.BrainUsage,
      useFactory: (db: PrismaService) => new PrismaBrainUsageRepository(db),
      inject: [PrismaService],
    },
    { provide: TOKENS.Kernel, useValue: new DeterministicKernel() },
    { provide: TOKENS.Payment, useValue: new MockPaymentProvider() },
    {
      provide: TOKENS.Knowledge,
      useFactory: (db: PrismaService) => new PrismaKnowledgeChunkRepository(db),
      inject: [PrismaService],
    },
    {
      provide: TOKENS.KnowledgeDocuments,
      useFactory: (db: PrismaService) => new PrismaKnowledgeDocumentRepository(db),
      inject: [PrismaService],
    },
    {
      provide: TOKENS.KnowledgeRetrieval,
      useFactory: (brain: AgentBrainPort, knowledge: KnowledgeChunkRepository) =>
        new KnowledgeRetriever({ brain, knowledge }),
      inject: [TOKENS.Brain, TOKENS.Knowledge],
    },
    {
      provide: TOKENS.ChatSessions,
      useFactory: (db: PrismaService) => new PrismaChatSessionRepository(db),
      inject: [PrismaService],
    },
    {
      provide: TOKENS.ChatMessages,
      useFactory: (db: PrismaService) => new PrismaChatMessageRepository(db),
      inject: [PrismaService],
    },
    {
      provide: TOKENS.Integrations,
      useFactory: (db: PrismaService) => new PrismaIntegrationRepository(db),
      inject: [PrismaService],
    },
    { provide: TOKENS.RepoProvider, useValue: new MockRepoProvider() },
    { provide: TOKENS.SecretVault, useValue: new StubSecretVault() },
  ],
  exports: [
    PrismaService,
    TOKENS.Users,
    TOKENS.Orgs,
    TOKENS.Memberships,
    TOKENS.Sessions,
    TOKENS.Projects,
    TOKENS.Slices,
    TOKENS.Features,
    TOKENS.Scenarios,
    TOKENS.TestCases,
    TOKENS.Runs,
    TOKENS.RunResults,
    TOKENS.Agents,
    TOKENS.ToolBindings,
    TOKENS.Subscriptions,
    TOKENS.Audit,
    TOKENS.UnitOfWork,
    TOKENS.Hasher,
    TOKENS.Ids,
    TOKENS.Tokens,
    TOKENS.Clock,
    TOKENS.Brain,
    TOKENS.BrainKeys,
    TOKENS.BrainUsage,
    TOKENS.Events,
    TOKENS.Kernel,
    TOKENS.Payment,
    TOKENS.Knowledge,
    TOKENS.KnowledgeDocuments,
    TOKENS.KnowledgeRetrieval,
    TOKENS.ChatSessions,
    TOKENS.ChatMessages,
    TOKENS.Integrations,
    TOKENS.RepoProvider,
    TOKENS.SecretVault,
  ],
})
export class PrismaPersistenceModule {}
